apiVersion: apps/v1
kind: Deployment
metadata:
  name: quic-broker
  labels:
    app: quic-broker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: quic-broker
  template:
    metadata:
      labels:
        app: quic-broker
    spec:
      containers:
        - name: quic-broker
          image: ghcr.io/mohammadiahmad/quicmessagebroker/quic-broker:0.0.4
          ports:
            - containerPort: 4040
              protocol: UDP
          args: ["server"]
          env:
            - name: QUIC__SERVER__HOST
              value: "0.0.0.0"
            - name: QUIC__SERVER__PORT
              value: "4040"
            - name: QUIC__SERVER__MSG_COUNT
              value: "1000"
            - name: QUIC__SERVER__RATE_LIMIT
              value: "100"

