apiVersion: v1
kind: Service
metadata:
  name: quic-svc-lb
spec:
  type: LoadBalancer
  ports:
    - name: "4040-udp"
      targetPort: 4040
      port: 4040
      protocol: UDP
  selector:
    app: quic-broker

